# Generated by Django 4.2.11 on 2025-12-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Уникальное название скважины (например, 'Скважина №1')", max_length=100, unique=True, verbose_name='Название скважины')),
                ('depth', models.FloatField(help_text='Общая глубина скважины, метров', verbose_name='Глубина скважины')),
                ('diameter', models.FloatField(help_text='Диаметр эксплуатационной колонны, миллиметров', verbose_name='Диаметр колонны')),
                ('pump_depth', models.FloatField(help_text='Глубина установки ЭЦН, метров', verbose_name='Глубина спуска насоса')),
                ('dynamic_level', models.FloatField(help_text='Уровень жидкости при работе насоса, метров', verbose_name='Динамический уровень')),
                ('static_level', models.FloatField(help_text='Уровень жидкости в покое, метров', verbose_name='Статический уровень')),
                ('formation_debit', models.FloatField(help_text='Расчетный дебит скважины, м³/сутки', verbose_name='Пластовый дебит')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время добавления скважины в систему', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления данных', verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Скважина',
                'verbose_name_plural': 'Скважины',
                'ordering': ['name'],
            },
        ),
    ]
