# Generated by Django 6.0.1 on 2026-03-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='gas_factor',
            field=models.FloatField(default=50.0, help_text='Газосодержание м³/т', verbose_name='Газовый фактор'),
        ),
        migrations.AlterField(
            model_name='well',
            name='oil_density',
            field=models.FloatField(default=850.0, help_text='Плотность сепарированной нефти в поверхностных условиях, кг/м³', verbose_name='Плотность нефти'),
        ),
        migrations.AlterField(
            model_name='well',
            name='water_density',
            field=models.FloatField(default=1170.0, help_text='Плотность пластовой воды, кг/м³', verbose_name='Плотность воды'),
        ),
        migrations.AddIndex(
            model_name='telemetrydata',
            index=models.Index(fields=['-timestamp'], name='core_teleme_timesta_b4784e_idx'),
        ),
    ]
